### ISSUE TITLE
Switch lab order

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/orm-mapping-to-tables#29]
Hi, I would recommend having the Pokemon Scraper lab come after this lesson. While I was doing it I felt very lost and didn't feel like I was prepped at all (plus there was bonus!). Unless the intention is for us to struggle and figure it out ourselves (without actually understanding how the code works), I think it would make more sense to switch up the order.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30. We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @arianaberger,

Thank you for providing this feedback. The pokemon scraper lab had unfortunately been misordered. We've corrected the order of these lessons and believe this issue is now resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
