### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/orm-mapping-to-tables#30]
PROBLEM: Reconsider lab placement. See issue #29.
NOTIFY: @arianaberger

**Comment by maxwellbenton** [comment]
This issue was due to a error in positioning of ORM pokemon lab (https://github.com/learn-co-curriculum/pokemon-scraper). At some point, this pokemon lab was likely dragged and dropped into the second position in the section on ORMs, directly after the intro to what ORMs are but way before the concepts are introduced that are needed to solve the lab. This was resolved in Spring 2019 and no new issues have been opened since. This issue should now be resolved.
