### ISSUE TITLE
Lesson placement

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/orm-mapping-to-tables#34]
This lesson would be really helpful prior to the first lab in this section. :)

**Comment by maxwellbenton** [comment]
Hi @helloamandamurphy,

Thank you for providing this feedback. We were able to confirm that The prior lab had been misplaced too early in this section. We've reordered the content so that the lab is properly set up with necessary lessons beforehand.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
